import { EffectDefinition } from '@/types/effect';

/**
 * Effects Registry – every filter here is tuned to match real-world aesthetics:
 *  - cssFilter: quick GPU path for base exposure/colour shift
 *  - pixelGrade: per-pixel LUT-style colour grade (applied after cssFilter)
 *  - overlayType: canvas overlay (vignette / grain / leak / scanlines …)
 */
export const EFFECTS_REGISTRY: EffectDefinition[] = [

  // ─── ORIGINAL ────────────────────────────────────────────────────────────────
  {
    id: 'normal',
    name: 'Original',
    category: 'color',
    description: 'Clean natural camera feed without any colour grading',
    thumbnailColor: 'bg-zinc-700',
    cssFilter: 'none',
  },

  // ─── INSTAGRAM FILTERS ────────────────────────────────────────────────────────
  {
    id: 'instagram-clarendon',
    name: 'Clarendon',
    category: 'instagram',
    description: 'Vibrant, high-contrast look with cool lifted shadows — the most used Instagram filter',
    thumbnailColor: 'bg-blue-500',
    cssFilter: 'contrast(1.4) brightness(1.1) saturate(1.5)',
    pixelGrade: 'clarendon',
  },
  {
    id: 'instagram-paris',
    name: 'Paris',
    category: 'instagram',
    description: 'Warm pastel glow with subtle skin smoothing',
    thumbnailColor: 'bg-pink-300',
    cssFilter: 'brightness(1.1) contrast(0.85) saturate(1.3)',
    pixelGrade: 'paris',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'instagram-valencia',
    name: 'Valencia',
    category: 'instagram',
    description: 'Faded antique warmth with lifted blacks and golden light leak',
    thumbnailColor: 'bg-amber-500',
    cssFilter: 'sepia(0.35) contrast(1.15) brightness(1.1) saturate(1.4)',
    pixelGrade: 'valencia',
    overlayType: 'light-leak',
  },
  {
    id: 'instagram-tokyo',
    name: 'Tokyo',
    category: 'instagram',
    description: 'Dramatic warm monochrome portrait finish',
    thumbnailColor: 'bg-zinc-900',
    cssFilter: 'grayscale(1) contrast(1.5) brightness(1.05)',
    pixelGrade: 'tokyo',
    overlayType: 'vignette',
  },
  {
    id: 'instagram-lark',
    name: 'Lark',
    category: 'instagram',
    description: 'Desaturated, airy, cool-blue shadows with bright whites',
    thumbnailColor: 'bg-sky-200',
    cssFilter: 'brightness(1.15) contrast(0.85) saturate(0.7) hue-rotate(15deg)',
  },
  {
    id: 'instagram-juno',
    name: 'Juno',
    category: 'instagram',
    description: 'Warm tones, punchy saturation, slight green mid-lift',
    thumbnailColor: 'bg-emerald-600',
    cssFilter: 'contrast(1.3) saturate(1.6) hue-rotate(-12deg) brightness(1.05)',
    pixelGrade: 'golden',
  },
  {
    id: 'instagram-gingham',
    name: 'Gingham',
    category: 'instagram',
    description: 'Vintage yellow fade with low contrast and warm whites',
    thumbnailColor: 'bg-yellow-100',
    cssFilter: 'sepia(0.2) brightness(1.1) contrast(0.8) saturate(0.7) hue-rotate(-10deg)',
    pixelGrade: 'polaroid',
  },

  // ─── VINTAGE / FILM ──────────────────────────────────────────────────────────
  {
    id: 'vintage',
    name: 'Real Vintage 35mm',
    category: 'film',
    description: 'Authentic 35mm warm sepia grade with vignette, sun flare & real film grain',
    thumbnailColor: 'bg-amber-800',
    cssFilter: 'sepia(0.6) contrast(1.3) brightness(0.9) saturate(1.4) hue-rotate(-10deg)',
    overlayType: 'real-vintage',
  },
  {
    id: 'disposable-90s',
    name: '90s Disposable',
    category: 'film',
    description: 'Overexposed point-and-shoot flash look with warm light leak',
    thumbnailColor: 'bg-yellow-600',
    cssFilter: 'contrast(1.4) brightness(1.25) saturate(1.5) hue-rotate(5deg)',
    overlayType: 'light-leak',
  },
  {
    id: 'film-grain-35mm',
    name: '35mm Film Grain',
    category: 'film',
    description: 'Silver halide film texture with authentic luminance-sensitive grain',
    thumbnailColor: 'bg-stone-700',
    cssFilter: 'contrast(1.2) saturate(0.8) brightness(0.95)',
    pixelGrade: 'film35mm',
    overlayType: 'grain',
  },
  {
    id: 'polaroid-vintage',
    name: 'Polaroid Instant',
    category: 'film',
    description: 'Faded instant camera film — warm highlights, lifted shadows',
    thumbnailColor: 'bg-orange-100',
    cssFilter: 'sepia(0.3) contrast(1.15) brightness(1.1) saturate(1.2)',
    pixelGrade: 'polaroid',
    overlayType: 'vignette',
  },
  {
    id: 'vhs-tape',
    name: 'VHS Retro',
    category: 'film',
    description: 'Analog cassette tape look with scanlines and colour bleed',
    thumbnailColor: 'bg-indigo-800',
    cssFilter: 'contrast(1.3) saturate(1.5) hue-rotate(-15deg) brightness(0.9)',
    pixelGrade: 'vhs',
    glShader: 'scanlines',
  },
  {
    id: 'super8',
    name: 'Super 8 Film',
    category: 'film',
    description: 'Warm 8mm home movie look with heavy grain and orange cast',
    thumbnailColor: 'bg-amber-700',
    cssFilter: 'sepia(0.7) contrast(1.3) brightness(0.85) saturate(1.6) hue-rotate(-15deg)',
    overlayType: 'real-vintage',
  },

  // ─── BEAUTY & PORTRAIT ───────────────────────────────────────────────────────
  {
    id: 'portrait-blur',
    name: 'Portrait Blur',
    category: 'beauty',
    description: 'Smooth background bokeh with sharp subject — like iPhone portrait mode',
    thumbnailColor: 'bg-indigo-500',
    overlayType: 'portrait-blur',
  },
  {
    id: 'beauty-smooth',
    name: 'Beauty Smooth',
    category: 'beauty',
    description: 'Luminous skin-softening glow with radiant portrait finish',
    thumbnailColor: 'bg-rose-300',
    cssFilter: 'brightness(1.12) contrast(0.85) saturate(1.15)',
    pixelGrade: 'paris',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'korean-glow',
    name: 'Korean Glass Skin',
    category: 'beauty',
    description: 'Airy dewy luminosity — glassy bright skin tones',
    thumbnailColor: 'bg-rose-100',
    cssFilter: 'brightness(1.2) contrast(0.8) saturate(1.3) hue-rotate(-5deg)',
    pixelGrade: 'korean-glow',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'studio-light',
    name: 'Studio Light',
    category: 'beauty',
    description: 'Soft front-lit studio portrait with clean crisp skin tones',
    thumbnailColor: 'bg-neutral-100',
    cssFilter: 'brightness(1.2) contrast(1.05) saturate(0.85)',
    overlayType: 'beauty-smooth',
  },

  // ─── COLOUR GRADES ────────────────────────────────────────────────────────────
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'color',
    description: 'Late afternoon amber sunshine warmth',
    thumbnailColor: 'bg-amber-500',
    cssFilter: 'brightness(1.1) saturate(1.6) sepia(0.4) hue-rotate(-12deg)',
    pixelGrade: 'golden',
  },
  {
    id: 'cyberpunk',
    name: 'Cyber Neon',
    category: 'color',
    description: 'Electric neon cyan-magenta split with deep shadows',
    thumbnailColor: 'bg-fuchsia-800',
    cssFilter: 'contrast(1.5) saturate(2) hue-rotate(55deg) brightness(0.9)',
    pixelGrade: 'cyberpunk',
    overlayType: 'vignette-heavy',
  },
  {
    id: 'noir',
    name: 'Classic Noir',
    category: 'color',
    description: 'High-contrast dramatic monochrome silver print',
    thumbnailColor: 'bg-zinc-950',
    cssFilter: 'grayscale(1) contrast(1.6) brightness(0.85)',
    pixelGrade: 'noir',
    overlayType: 'vignette',
  },
  {
    id: 'cinematic-teal-orange',
    name: 'Cinematic Teal & Orange',
    category: 'color',
    description: 'Hollywood teal-shadow orange-highlight LUT — blockbuster grade',
    thumbnailColor: 'bg-cyan-800',
    cssFilter: 'contrast(1.3) saturate(1.2) brightness(0.9)',
    pixelGrade: 'cinematic',
    overlayType: 'vignette',
  },
  {
    id: 'overcast',
    name: 'Overcast',
    category: 'color',
    description: 'Muted, desaturated Scandinavian cool palette',
    thumbnailColor: 'bg-slate-400',
    cssFilter: 'saturate(0.4) contrast(1.15) brightness(1.1) hue-rotate(10deg)',
  },

  // ─── TEXTURES ─────────────────────────────────────────────────────────────────
  {
    id: 'dust-scratches',
    name: 'Dust & Film Specs',
    category: 'texture',
    description: 'Physical film surface dust particles and hair scratches',
    thumbnailColor: 'bg-stone-600',
    cssFilter: 'contrast(1.3) sepia(0.15)',
    overlayType: 'dust',
  },
  {
    id: 'light-leak-warm',
    name: 'Warm Light Leak',
    category: 'texture',
    description: 'Sun flare orange-amber exposure bleed across the frame',
    thumbnailColor: 'bg-orange-500',
    cssFilter: 'brightness(1.1) saturate(1.3)',
    overlayType: 'light-leak',
  },

  // ─── LENS & OPTICAL ───────────────────────────────────────────────────────────
  {
    id: 'vignette-heavy',
    name: 'Lomo Vignette',
    category: 'lens',
    description: 'Dramatic Lomo-style edge darkening — draws eye to centre',
    thumbnailColor: 'bg-neutral-900',
    cssFilter: 'contrast(1.4) saturate(1.3)',
    overlayType: 'vignette-heavy',
  },
  {
    id: 'soft-vignette',
    name: 'Soft Vignette',
    category: 'lens',
    description: 'Gentle edge fade for classic portrait framing',
    thumbnailColor: 'bg-neutral-600',
    cssFilter: 'contrast(1.15)',
    overlayType: 'vignette',
  },

  // ─── DIGITAL & GLITCH ────────────────────────────────────────────────────────
  {
    id: 'cartoon',
    name: 'Cartoon / Cel Shade',
    category: 'digital',
    description: 'Posterized comic book style with vibrant colours',
    thumbnailColor: 'bg-yellow-400',
    cssFilter: 'contrast(1.6) saturate(1.8)',
    pixelGrade: 'cartoon',
  },
  {
    id: 'pixelate',
    name: '8-Bit Pixel',
    category: 'digital',
    description: 'Retro 8-bit video game pixel art style',
    thumbnailColor: 'bg-green-500',
    cssFilter: 'contrast(1.4) saturate(1.8)',
    glShader: 'pixelate',
  },
  {
    id: 'rgb-split',
    name: 'RGB Glitch',
    category: 'digital',
    description: 'Chromatic aberration channel displacement — digital glitch art',
    thumbnailColor: 'bg-red-800',
    glShader: 'rgbShift',
  },
  {
    id: 'crt-monitor',
    name: 'CRT Monitor',
    category: 'digital',
    description: 'Retro tube TV with visible scanlines and phosphor glow',
    thumbnailColor: 'bg-green-900',
    cssFilter: 'contrast(1.3) saturate(1.3) brightness(0.85)',
    glShader: 'scanlines',
    overlayType: 'vignette',
  },
  
  // ─── AR PROPS ────────────────────────────────────────────────────────
  {
    id: 'prop-sunglasses',
    name: 'Sunglasses',
    category: 'prop',
    description: 'AR Sunglasses mapped to your face',
    thumbnailColor: 'bg-zinc-800',
    cssFilter: 'none',
    propType: 'sunglasses',
  },
  {
    id: 'prop-cowboy-hat',
    name: 'Cowboy Hat',
    category: 'prop',
    description: 'AR Cowboy Hat mapped to your head',
    thumbnailColor: 'bg-amber-900',
    cssFilter: 'none',
    propType: 'cowboy-hat',
  },
];
