import { EffectDefinition } from '@/types/effect';

/**
 * Effects Registry – every filter here is tuned to match real-world aesthetics:
 *  - cssFilter: quick GPU path for base exposure/colour shift
 *  - pixelGrade: per-pixel LUT-style colour grade (applied after cssFilter)
 *  - overlayType: canvas overlay (vignette / grain / leak / scanlines …)
 */
export const EFFECTS_REGISTRY: EffectDefinition[] = [

  // ─── ORIGINAL ────────────────────────────────────────────────────────────────
  {
    id: 'normal',
    name: 'Original',
    category: 'color',
    description: 'Clean natural camera feed without any colour grading',
    thumbnailColor: 'bg-zinc-700',
    cssFilter: 'none',
  },

  // ─── INSTAGRAM FILTERS ────────────────────────────────────────────────────────
  {
    id: 'instagram-clarendon',
    name: 'Clarendon',
    category: 'instagram',
    description: 'Vibrant, high-contrast look with cool lifted shadows — the most used Instagram filter',
    thumbnailColor: 'bg-blue-500',
    cssFilter: 'contrast(1.2) brightness(1.06) saturate(1.25)',
    pixelGrade: 'clarendon',
  },
  {
    id: 'instagram-paris',
    name: 'Paris',
    category: 'instagram',
    description: 'Warm pastel glow with subtle skin smoothing',
    thumbnailColor: 'bg-pink-300',
    cssFilter: 'brightness(1.06) contrast(0.93) saturate(1.1)',
    pixelGrade: 'paris',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'instagram-valencia',
    name: 'Valencia',
    category: 'instagram',
    description: 'Faded antique warmth with lifted blacks and golden light leak',
    thumbnailColor: 'bg-amber-500',
    cssFilter: 'sepia(0.22) contrast(1.05) brightness(1.04) saturate(1.15)',
    pixelGrade: 'valencia',
    overlayType: 'light-leak',
  },
  {
    id: 'instagram-tokyo',
    name: 'Tokyo',
    category: 'instagram',
    description: 'Dramatic warm monochrome portrait finish',
    thumbnailColor: 'bg-zinc-900',
    cssFilter: 'grayscale(0.9) contrast(1.3) brightness(1.03)',
    pixelGrade: 'tokyo',
    overlayType: 'vignette',
  },
  {
    id: 'instagram-lark',
    name: 'Lark',
    category: 'instagram',
    description: 'Desaturated, airy, cool-blue shadows with bright whites',
    thumbnailColor: 'bg-sky-200',
    cssFilter: 'brightness(1.08) contrast(0.92) saturate(0.88) hue-rotate(8deg)',
  },
  {
    id: 'instagram-juno',
    name: 'Juno',
    category: 'instagram',
    description: 'Warm tones, punchy saturation, slight green mid-lift',
    thumbnailColor: 'bg-emerald-600',
    cssFilter: 'contrast(1.12) saturate(1.3) hue-rotate(-8deg) brightness(1.02)',
    pixelGrade: 'golden',
  },
  {
    id: 'instagram-gingham',
    name: 'Gingham',
    category: 'instagram',
    description: 'Vintage yellow fade with low contrast and warm whites',
    thumbnailColor: 'bg-yellow-100',
    cssFilter: 'sepia(0.1) brightness(1.06) contrast(0.9) saturate(0.85) hue-rotate(-5deg)',
    pixelGrade: 'polaroid',
  },

  // ─── VINTAGE / FILM ──────────────────────────────────────────────────────────
  {
    id: 'vintage',
    name: 'Real Vintage 35mm',
    category: 'film',
    description: 'Authentic 35mm warm sepia grade with vignette, sun flare & real film grain',
    thumbnailColor: 'bg-amber-800',
    cssFilter: 'sepia(0.4) contrast(1.12) brightness(0.97) saturate(1.18) hue-rotate(-6deg)',
    overlayType: 'real-vintage',
  },
  {
    id: 'disposable-90s',
    name: '90s Disposable',
    category: 'film',
    description: 'Overexposed point-and-shoot flash look with warm light leak',
    thumbnailColor: 'bg-yellow-600',
    cssFilter: 'contrast(1.22) brightness(1.14) saturate(1.28) hue-rotate(3deg)',
    overlayType: 'light-leak',
  },
  {
    id: 'film-grain-35mm',
    name: '35mm Film Grain',
    category: 'film',
    description: 'Silver halide film texture with authentic luminance-sensitive grain',
    thumbnailColor: 'bg-stone-700',
    cssFilter: 'contrast(1.08) saturate(0.95) brightness(0.98)',
    pixelGrade: 'film35mm',
    overlayType: 'grain',
  },
  {
    id: 'polaroid-vintage',
    name: 'Polaroid Instant',
    category: 'film',
    description: 'Faded instant camera film — warm highlights, lifted shadows',
    thumbnailColor: 'bg-orange-100',
    cssFilter: 'sepia(0.18) contrast(1.0) brightness(1.06) saturate(1.08)',
    pixelGrade: 'polaroid',
    overlayType: 'vignette',
  },
  {
    id: 'vhs-tape',
    name: 'VHS Retro',
    category: 'film',
    description: 'Analog cassette tape look with scanlines and colour bleed',
    thumbnailColor: 'bg-indigo-800',
    cssFilter: 'contrast(1.12) saturate(1.2) hue-rotate(-8deg) brightness(0.96)',
    pixelGrade: 'vhs',
    glShader: 'scanlines',
  },
  {
    id: 'super8',
    name: 'Super 8 Film',
    category: 'film',
    description: 'Warm 8mm home movie look with heavy grain and orange cast',
    thumbnailColor: 'bg-amber-700',
    cssFilter: 'sepia(0.5) contrast(1.18) brightness(0.94) saturate(1.35) hue-rotate(-10deg)',
    overlayType: 'real-vintage',
  },

  // ─── BEAUTY & PORTRAIT ───────────────────────────────────────────────────────
  {
    id: 'portrait-blur',
    name: 'Portrait Blur',
    category: 'beauty',
    description: 'Smooth background bokeh with sharp subject — like iPhone portrait mode',
    thumbnailColor: 'bg-indigo-500',
    overlayType: 'portrait-blur',
  },
  {
    id: 'beauty-smooth',
    name: 'Beauty Smooth',
    category: 'beauty',
    description: 'Luminous skin-softening glow with radiant portrait finish',
    thumbnailColor: 'bg-rose-300',
    cssFilter: 'brightness(1.06) contrast(0.95) saturate(1.06)',
    pixelGrade: 'paris',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'korean-glow',
    name: 'Korean Glass Skin',
    category: 'beauty',
    description: 'Airy dewy luminosity — glassy bright skin tones',
    thumbnailColor: 'bg-rose-100',
    cssFilter: 'brightness(1.1) contrast(0.9) saturate(1.12) hue-rotate(-3deg)',
    pixelGrade: 'korean-glow',
    overlayType: 'beauty-smooth',
  },
  {
    id: 'studio-light',
    name: 'Studio Light',
    category: 'beauty',
    description: 'Soft front-lit studio portrait with clean crisp skin tones',
    thumbnailColor: 'bg-neutral-100',
    cssFilter: 'brightness(1.12) contrast(0.97) saturate(0.94)',
    overlayType: 'beauty-smooth',
  },

  // ─── COLOUR GRADES ────────────────────────────────────────────────────────────
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    category: 'color',
    description: 'Late afternoon amber sunshine warmth',
    thumbnailColor: 'bg-amber-500',
    cssFilter: 'brightness(1.04) saturate(1.38) sepia(0.28) hue-rotate(-8deg)',
    pixelGrade: 'golden',
  },
  {
    id: 'cyberpunk',
    name: 'Cyber Neon',
    category: 'color',
    description: 'Electric neon cyan-magenta split with deep shadows',
    thumbnailColor: 'bg-fuchsia-800',
    cssFilter: 'contrast(1.28) saturate(1.65) hue-rotate(42deg) brightness(0.98)',
    pixelGrade: 'cyberpunk',
    overlayType: 'vignette-heavy',
  },
  {
    id: 'noir',
    name: 'Classic Noir',
    category: 'color',
    description: 'High-contrast dramatic monochrome silver print',
    thumbnailColor: 'bg-zinc-950',
    cssFilter: 'grayscale(1) contrast(1.35) brightness(0.93)',
    pixelGrade: 'noir',
    overlayType: 'vignette',
  },
  {
    id: 'cinematic-teal-orange',
    name: 'Cinematic Teal & Orange',
    category: 'color',
    description: 'Hollywood teal-shadow orange-highlight LUT — blockbuster grade',
    thumbnailColor: 'bg-cyan-800',
    cssFilter: 'contrast(1.18) saturate(1.05) brightness(0.97)',
    pixelGrade: 'cinematic',
    overlayType: 'vignette',
  },
  {
    id: 'overcast',
    name: 'Overcast',
    category: 'color',
    description: 'Muted, desaturated Scandinavian cool palette',
    thumbnailColor: 'bg-slate-400',
    cssFilter: 'saturate(0.65) contrast(1.05) brightness(1.04) hue-rotate(5deg)',
  },

  // ─── TEXTURES ─────────────────────────────────────────────────────────────────
  {
    id: 'dust-scratches',
    name: 'Dust & Film Specs',
    category: 'texture',
    description: 'Physical film surface dust particles and hair scratches',
    thumbnailColor: 'bg-stone-600',
    cssFilter: 'contrast(1.1) sepia(0.08)',
    overlayType: 'dust',
  },
  {
    id: 'light-leak-warm',
    name: 'Warm Light Leak',
    category: 'texture',
    description: 'Sun flare orange-amber exposure bleed across the frame',
    thumbnailColor: 'bg-orange-500',
    cssFilter: 'brightness(1.04) saturate(1.15)',
    overlayType: 'light-leak',
  },

  // ─── LENS & OPTICAL ───────────────────────────────────────────────────────────
  {
    id: 'vignette-heavy',
    name: 'Lomo Vignette',
    category: 'lens',
    description: 'Dramatic Lomo-style edge darkening — draws eye to centre',
    thumbnailColor: 'bg-neutral-900',
    cssFilter: 'contrast(1.22) saturate(1.18)',
    overlayType: 'vignette-heavy',
  },
  {
    id: 'soft-vignette',
    name: 'Soft Vignette',
    category: 'lens',
    description: 'Gentle edge fade for classic portrait framing',
    thumbnailColor: 'bg-neutral-600',
    cssFilter: 'contrast(1.05)',
    overlayType: 'vignette',
  },

  // ─── DIGITAL & GLITCH ────────────────────────────────────────────────────────
  {
    id: 'cartoon',
    name: 'Cartoon / Cel Shade',
    category: 'digital',
    description: 'Posterized comic book style with vibrant colours',
    thumbnailColor: 'bg-yellow-400',
    cssFilter: 'contrast(1.4) saturate(1.5)',
    pixelGrade: 'cartoon',
  },
  {
    id: 'pixelate',
    name: '8-Bit Pixel',
    category: 'digital',
    description: 'Retro 8-bit video game pixel art style',
    thumbnailColor: 'bg-green-500',
    cssFilter: 'contrast(1.2) saturate(1.4)',
    glShader: 'pixelate',
  },
  {
    id: 'rgb-split',
    name: 'RGB Glitch',
    category: 'digital',
    description: 'Chromatic aberration channel displacement — digital glitch art',
    thumbnailColor: 'bg-red-800',
    glShader: 'rgbShift',
  },
  {
    id: 'crt-monitor',
    name: 'CRT Monitor',
    category: 'digital',
    description: 'Retro tube TV with visible scanlines and phosphor glow',
    thumbnailColor: 'bg-green-900',
    cssFilter: 'contrast(1.15) saturate(1.1) brightness(0.95)',
    glShader: 'scanlines',
    overlayType: 'vignette',
  },
];
